# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 04:30
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.upload_location),
        ),
    ]
